version: '3.7'

services:

  frontend:
    build:
      context: client
    container_name: frontend
    ports:
      - 80:5000
    networks:
      - drinkCounter

  backend:
    build:
      context: server
    container_name: backend
    ports:
      - 5000:5000
      - 8000:8000
    networks:
      - drinkCounter

  postgres:
    build:
      context: database
    container_name: database
    volumes:
      - drinkCounter:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: suP3rs3cRe7
      POSTGRES_USER: sgfo
      POSTGRES_DB: sgfo
    networks:
      - drinkCounter

volumes:
  drinkCounter:

networks:
  drinkCounter:
